{
 "title": "Switch2",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   { "name": "sum_of_fixed_rates", "label": "daily_fixed", "query": "0.9579" },
   { "name": "water_fixed_daily", "label": "water_daily", "query": "0.044667" },
   { "name": "sewerage_fixed_daily", "label": "sewerage_daily", "query": "0.05133" },
   { "name": "elec_fixed_daily", "label": "elec_daily", "query": "0.142" },
   { "name": "heat_fixed_daily", "label": "heat_daily", "query": "0.72" },
   { "name": "water_unit_cost", "query": "1.365" },
   { "name": "heat_unit_cost", "query": "0.0695" },
   { "name": "elec_unit_cost", "query": "0.135" },
   { "name": "sewerage_unit_cost", "query": "0.826" }
  ]
 },
 "panels": [
  {
   "title": "Water Usage over time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volume",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT last(\"measurement\") - first(\"measurement\") AS \"Volume\" FROM \"Switch2\" WHERE (\"type\" = 'Water') AND $timeFilter",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Water" }
     ]
    },
    {
     "alias": "Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT (last(\"measurement\")*last(\"unit_cost\") - first(\"measurement\")*last(\"unit_cost\")) as \"cost\" FROM \"Switch2\" WHERE (\"type\" = 'Water') AND $timeFilter",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Water" }
     ]
    }
   ]
  },
  {
   "title": "Heat Usage over time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT last(\"measurement\") - first(\"measurement\") AS \"Volume\" FROM \"Switch2\" WHERE (\"type\" = 'Heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Water" }
     ]
    },
    {
     "alias": "Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT (last(\"measurement\")*last(\"unit_cost\") - first(\"measurement\")*last(\"unit_cost\")) as \"cost\" FROM \"Switch2\" WHERE (\"type\" = 'Heat') AND $timeFilter",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Water" }
     ]
    }
   ]
  },
  {
   "title": "Electricity Usage over time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT last(\"measurement\") - first(\"measurement\") AS \"Volume\" FROM \"Switch2\" WHERE (\"type\" = 'Electricity') AND $timeFilter",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Water" }
     ]
    },
    {
     "alias": "Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT (last(\"measurement\")*last(\"unit_cost\") - first(\"measurement\")*last(\"unit_cost\")) as \"cost\" FROM \"Switch2\" WHERE (\"type\" = 'Electricity') AND $timeFilter",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Water" }
     ]
    }
   ]
  },
  {
   "title": "Sewerage Usage over time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volume",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT last(\"measurement\") - first(\"measurement\") AS \"Volume\" FROM \"Switch2\" WHERE (\"type\" = 'Sewerage') AND $timeFilter",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Water" }
     ]
    },
    {
     "alias": "Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT (last(\"measurement\")*last(\"unit_cost\") - first(\"measurement\")*last(\"unit_cost\")) as \"cost\" FROM \"Switch2\" WHERE (\"type\" = 'Sewerage') AND $timeFilter",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Water" }
     ]
    }
   ]
  },
  {
   "title": "Fixed Rate in Time-Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Switch2",
     "query": "SELECT count(\"fix_rate\")*$sum_of_fixed_rates FROM \"Switch2\" WHERE (\"type\" = 'Electricity') AND $timeFilter",
     "select": [
      [
       { "params": [ "fix_rate" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Electricity" }
     ]
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Use Per Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Electricity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Electricity" }
     ]
    }
   ]
  },
  {
   "title": "Heat Use Per Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Heat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Heat" }
     ]
    }
   ]
  },
  {
   "title": "Bill Total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "alias": "Fixed Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT sum(\"fix_rate\") FROM \"Switch2\" WHERE (time >= 1577836800000ms and time <= 1609372800000ms) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "fix_rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Electricity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT (difference(last(\"measurement\")))*(last(\"unit_cost\")) FROM \"Switch2\" WHERE (\"type\" = 'Electricity') AND (time >= 1577836800000ms and time <= 1609372800000ms) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Heat" }
     ]
    },
    {
     "alias": "Heat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT (difference(last(\"measurement\")))*(last(\"unit_cost\")) FROM \"Switch2\" WHERE (\"type\" = 'Heat') AND (time >= 1577836800000ms and time <= 1609372800000ms) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Heat" }
     ]
    },
    {
     "alias": "Water",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT (difference(last(\"measurement\")))*(last(\"unit_cost\")) FROM \"Switch2\" WHERE (\"type\" = 'Water') AND (time >= 1577836800000ms and time <= 1609372800000ms) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Heat" }
     ]
    },
    {
     "alias": "Sewerage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT (difference(last(\"measurement\")))*(last(\"unit_cost\")) FROM \"Switch2\" WHERE (\"type\" = 'Sewerage') AND (time >= 1577836800000ms and time <= 1609372800000ms) GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Heat" }
     ]
    }
   ]
  },
  {
   "title": "Latest Raw",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Electricity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT mean(\"measurement\") as \"Electricity\" FROM \"Switch2\"  WHERE (\"type\" = 'Electricity') AND $timeFilter GROUP BY time($__interval) fill(none)  ORDER BY time DESC\nLIMIT 5",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Electricity" }
     ]
    },
    {
     "alias": "Electricity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT mean(\"measurement\") as \"Heat\" FROM \"Switch2\"  WHERE (\"type\" = 'Heat') AND $timeFilter GROUP BY time($__interval) fill(none)  ORDER BY time DESC\nLIMIT 5",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Electricity" }
     ]
    },
    {
     "alias": "Electricity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Switch2",
     "query": "SELECT mean(\"measurement\") as \"Water\" FROM \"Switch2\"  WHERE (\"type\" = 'Water') AND $timeFilter GROUP BY time($__interval) fill(none)  ORDER BY time DESC\nLIMIT 5",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Electricity" }
     ]
    }
   ]
  }
 ]
}